# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChirpReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ChirpReactNative
  pod 'ChirpSDK', '3.5.2'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end
